# Python callable()函数

> 原文:[https://codescracker . com/python/python-callable-function . htm](https://codescracker.com/python/python-callable-function.htm)

Python 中的 **callable()** 函数如果指定对象看起来是可调用的，则返回 **True** ，否则如果指定对象是不可调用的，则 返回 **False** 。例如:

```
def myf():
    num = 10

print(callable(myf))

val = 20
print(callable(val))
```

这个 Python 程序产生的输出展示了 **callable()** 函数:

```
True
False
```

**注-** If *callable()* 为指定对象返回 **True** 。那么对该对象的调用可能会失败。 但如果 *callable()* 为指定对象返回 **False** 。那么对该对象调用肯定会失败。

## Python callable()函数语法

Python 中 **callable()** 函数的语法是:

```
callable(obj)
```

其中 **obj** 指的是一个将要检查它是否是可调用对象的对象。

## Python callable()函数示例

下面是 Python 中 **callable()** 函数的一个简单例子。在这个程序中，我创建了一个类 **codescracker** 来检查它是否可调用，当然，使用的是 **callable()** 函数:

```
class CodesCracker:
    def __call__(self):
        print("python programming")

x = callable(codescracker)
if x:
    print("The class \"codescracker\" is callable")

    # following two statements proves, codescracker class is callable
    obj = codescracker()
    obj()
else:
    print("The class \"codescracker\" is not callable")
```

下面给出的快照显示了这个 Python 程序产生的示例输出:

![python callable function](../Images/fbce4dcb5e692e40d014d672b5476824.png)

现在让我们创建另一个没有 **__call__()** 的程序，来演示有时 *callable()* 为一个看似可调用的指定对象返回 *True* ，但实际上我们不能调用该对象:

```
class CodesCracker:
    def myf(self):
        print("python programming")

x = callable(codescracker)
if x:
    print("The class \"codescracker\" is callable")

    # Following two statements raises error
    # As this time the class's instance is actually not callable
    obj = codescracker()
    obj()
else:
    print("The class \"codescracker\" is not callable")
```

如果您执行这个程序，那么输出将是:

![python callable function example](../Images/703c76f31293f10ec26106fa5aee8bec.png)

因为使用语句:

```
x = callable(codescracker)
```

这里的方法 **callable()** 返回 **True** 。因此**为真**被初始化为 **x** 。而 因为 **x** 等于**真**，因此条件 **if x** 或 **if 真**评估为 **真**。如果块，程序流程进入[块。 和声明:](/python/python-if-else-elif-statements.htm)

```
print("The class \"codescracker\" is callable")
```

会被处决。所以我们看到了:

```
The class "codescracker" is callable
```

错误信息之前的输出。但是在使用下面两条语句时:

```
obj = codescracker()
obj()
```

实际上，使用最后一条语句，会引发一个名为 **TypeError** 的异常。因此不要只相信**上的**callable() 函数。也就是说，如果它返回 **True** ，那么就不要假设这个对象实际上是可调用的。但是， 您仍然可以使用 **except** 块捕获异常，方法是将上述两条语句(或最后一条语句， 用于调用的语句)放在 **try** 块中，如下所示:

```
class CodesCracker:
    def myf(self):
        print("python programming")

x = callable(codescracker)
if x:
    print("The class \"codescracker\" appears to be callable")
    obj = codescracker()
    try:
        obj()
    except TypeError:
        print("But actually is not callable")
else:
    print("The class \"codescracker\" is not callable")
```

现在，该程序产生的输出显示在下面给出的快照中:

![python callable function example](../Images/bdf4613a45a5b9e0e7f094a3e0c4e22a.png)

也就是说，如果程序在执行了 **try** 块中的语句后没有引发异常，意味着 该对象肯定是可调用的。因此你可以把对象可调用的所有东西放在 **try** 块中。

[Python 在线测试](/exam/showtest.php?subid=10)

* * *

* * *