# Java 异常处理

> 原文:[https://codescracker.com/java/java-exceptions.htm](https://codescracker.com/java/java-exceptions.htm)

在 Java 中，异常是运行时代码序列中出现的非自然情况。换句话说，异常是运行时错误。

在那些不支持异常处理的计算机语言中，必须手工检查和处理错误。

Java 中的异常处理将运行时错误管理带入了面向对象的世界。

在 Java 中，exception 是描述一段代码中发生的异常(即错误)情况的对象。

### 出现异常怎么办？

当出现异常情况时，会创建一个表示该异常的对象，并在导致错误的方法中引发该对象。该方法可能选择自己处理异常，或者传递异常。不管怎样，在某些时候，异常会被捕获并处理。

### 异常是如何产生的？

异常可以通过 Java 的运行时系统生成，也可以由您的代码手动生成。

Java 抛出的异常与违反 Java 语言规则或 Java 执行环境约束的基本错误有关。手动生成的异常通常用于向方法调用方报告一些错误情况。

### 如何管理异常？

Java 的异常处理通过以下五个关键字进行管理:

1.  尝试
2.  捕捉
3.  扔
4.  投
5.  最后

要监视异常的程序语句包含在 try 块中。如果 try 块中出现异常，就会引发异常。您的代码可以使用 catch 捕获这个异常，并以某种合理的方式处理它。系统生成的异常由 Java 的运行时系统自动抛出。若要手动引发异常，请使用 throw 关键字。任何从方法中抛出的异常都必须由 throws 子句指定。try 块完成后必须执行的任何代码都放在 finally 块中。

## Java 异常处理语法

下面是 Java 异常处理块的一般形式:

```
try {
   // block of the code to monitor for the errors

} catch(*ExceptionType1 exObj*) {
   // exception handler for *ExceptionType1*

} catch(*ExceptionType2 exObj*) {
   // exception handler for *ExceptionType2*
}
// ...
finally {
   // block of the code to be executed after try block ends
}
```

这里，ExceptionType 是已经发生的异常的类型。

## Java 异常类型

所有的异常类型都是 Throwable 内置类的子类。因此，Throwable 位于异常类层次结构的顶部。Throwable 下面是两个子类，它们将异常分成两个不同的分支。一个部门由例外领导。这个类用于用户程序应该捕捉的异常情况。这也是您在创建自定义异常类型时将继承的类。Exception 有一个重要的子类，叫做 RuntimeException。这种类型的异常是为您编写的程序自动定义的，包括像被零除和无效数组索引这样的事情。

另一个分支的顶部是 Error，它定义了在正常情况下程序不会捕捉到的异常。Java 的运行时系统使用 Error 类型的异常来指示与运行时环境本身有关的错误。堆栈溢出就是这种错误的一个例子。我们不会处理 Error 类型的异常，因为这些异常通常是为了应对程序通常无法处理的毁灭性故障而创建的。

下图显示了顶级异常层次结构:

![java exception handling](../Images/0b0cb3c1869a4b82f6669c9573023f10.png)

## Java 未捕获的异常

在学习如何在 Java 程序中处理异常之前，了解一下不处理异常时会发生什么是很有用的。下面的小程序包含一个故意导致被零除错误的表达式:

```
class Excp0 {
   public static void main(String args[]) {
      int denom = 0, num = 52;
      int res = num / denom;
   }
}
```

当 Java 的运行时系统检测到被零除的尝试时，它会构造一个新的异常对象，然后抛出这个异常。这导致 Excp0 的执行停止，因为一旦抛出异常，就必须通过异常处理程序捕获并立即处理。在这个例子中，我们没有提供任何自己的异常处理程序，因此异常被 Java 运行时系统提供的默认处理程序捕获。

程序没有捕捉到的任何异常最终都将由默认处理程序处理。默认处理程序显示描述异常的字符串，从异常发生的位置打印堆栈跟踪，并终止程序。

下面是执行此示例时生成的异常:

```
java.lang.ArithmeticException: / by zero
   at Excp0.main(Excp0.java:4)
```

注意这里的类名、 **Excp0** 、
、 方法名、 **main** 、
、 文件名、**、**、
、 和行号、 **4** 、
、 都包含在简单堆栈跟踪中。还要注意这里抛出的异常类型是异常的一个子类，叫做 ArithmeticException， ，它更具体地描述了发生了什么类型的错误。

堆栈跟踪将始终显示导致错误的方法调用的顺序。例如，下面是前面程序的另一个版本，它只是引入了相同的错误，但是使用了与 main()不同的方法:

```
class Excp1 {
   static void dividemethod() {
      int denom = 0, num = 20;
      int res = num / denom;
   }
   public static void main(String args[]) {
      Excp1.dividemethod();
   }
}
```

默认异常处理程序产生的堆栈跟踪显示了整个调用堆栈是如何显示的:

```
java.lang.ArithmeticException: / by zero
   at Excp1.dividemethod(Excp1.java:4)
   at Excp1.main(Excp1.java:7)
```

如您所见，堆栈的底部是 main 的第 7 行，这是对名为 dividemethod()的方法的调用，导致了第 4 行的异常。调用堆栈对于调试非常有用，因为它精确地指出了导致错误的步骤顺序。

[Java 在线测试](/exam/showtest.php?subid=1)

* * *

* * *