# Java 抛出和抛出

> 原文:[https://codescracker.com/java/java-throw-throws.htm](https://codescracker.com/java/java-throw-throws.htm)

## Java throw 语句

使用 **throw** 语句，可以为你的程序显式抛出一个异常。下面是在 Java 中使用 throw 语句的一般形式:

```
throw *ThrowableInstance*;
```

这里， *ThrowableInstance* 必须是 **Throwable** 类型的对象或者是 **Throwable** 的子类。

原语类型，如 **int** 或 **char** ，以及非 **Throwable** 类，如 **String** 和 **Object** ，不能使用 作为异常。

有两种方法可以获得一个 **Throwable** 对象，在 **catch** 子句中使用一个参数，或者用 **new** 操作符/关键字创建一个。

执行流程在**抛出**语句后立即停止，任何后续语句都不会被执行。检查最近的封闭 **try** 块，看它是否有与异常类型匹配的 **catch** 语句。如果找到匹配，控制被转移到该语句。如果不是，则检查下一个封闭的 **try** 语句，依此类推。如果没有找到匹配的 **catch** ，那么 默认的异常处理程序中止程序并打印堆栈跟踪。

## Java throw 示例

下面是一个简单的程序，它创建并抛出一个异常。捕获异常的处理程序将其重新抛出给外部处理程序。

```
/* Java Program Example - Java throw
 * This program demonstrate throw  */

 class JavaProgram
 {
     static void demometh() {
         try {

             throw new NullPointerException("demo");

         } catch(NullPointerException e) {

             System.out.println("Caught inside demometh");
             throw e;     // rethrow the exception

         }
     }

     public static void main(String args[])
     {

         try {

             demometh();

         } catch(NullPointerException e) {

             System.out.println("Recaught : " + e);

         }
     }
 }
```

这个程序有两次机会来处理同一个错误。首先， **main()** 建立一个异常上下文，然后调用 **demometh()** 。 **demo meth()**方法然后设置另一个异常处理上下文，并立即抛出一个新的 **NullPointerException** ， 实例，该实例在下一行被捕获。然后该异常被再次引发。以下是结果输出:

![java throw](../Images/426db4f4308b38128a6631a4b49030a4.png)

该程序还演示了如何创建一个 Java 的标准异常对象。请密切注意下面一行:

```
throw new NullPointerException("demo");
```

这里， **new** 操作符/关键字用于构造 **NullPointerException** 的一个实例。

许多 Java 的内置运行时异常至少有两个构造函数，一个不带参数，另一个带字符串参数。当使用第二种形式时，参数指定描述异常的字符串。当对象用作 **print()** 或 **println()** 的参数时，显示该字符串。也可以通过调用由 **Throwable** 定义的 **getMessage()** 来获得。

## Java 抛出

如果一个方法能够导致它不处理的异常，它必须指定这种行为，以便方法的调用方能够防范该异常。您可以通过在方法声明中包含一个 **throws** 子句来做到这一点。

一个 **throws** 子句列出了一个方法可能抛出的异常类型。这对于所有的异常都是必要的，除了那些**类型的 错误**或**运行时间异常**或它们的任何子类。方法可以抛出的所有其他异常必须在 **throws** 子句中声明 。否则，将会导致编译时错误。

下面是包含一个 **throws** 子句的方法声明的一般形式:

```
*type method-name(parameter-list)* throws *exception-list*
{
   // body of the method 
}
```

这里， *exception-list* 是一个以逗号分隔的方法可以抛出的异常列表。

## Java 抛出示例

下面是一个错误程序的例子，它试图抛出一个它没有捕捉到的异常。因为程序没有指定一个 **throws** 子句来声明这个事实，所以程序不会编译。

Java Programming Example Source Code (will not compile):

```
/* Java Program Example - Java throws
 * This program contains an error and
 * will not compile  */

 class JavaProgram
 {
     static void demometh() {

         System.out.println("Inside demometh");

         throw new IllegalAccessException("demo");

     }

     public static void main(String args[])
     {

         demometh();

     }
 }
```

要编译这个程序，您需要进行以下两项更改:

*   你需要声明 **demometh()** 抛出 **IllegalAccessException** 。
*   **main()** 必须定义一个 **try / catch** 语句来捕获这个异常。

现在，前面程序的修正版本如下所示:

```
/* Java Program Example - Java throws
 * This program is the correct version 
 * of the previous program  */

 class JavaProgram
 {
     static void demometh() throws IllegalAccessException {

         System.out.println("Inside demometh");

         throw new IllegalAccessException("demo");

     }

     public static void main(String args[])
     {

         try {

             demometh();

         } catch(IllegalAccessException e) {

             System.out.println("Caught " + e);

         }

     }
 }
```

当编译并执行上述 Java 程序时，它将产生以下输出:

![java throws](../Images/68eddc66b59364d97ab6c30a50beb802.png)

[Java 在线测试](/exam/showtest.php?subid=1)

* * *

* * *