# C++ 异常处理

> 原文：<https://codescracker.com/cpp/cpp-exception-handling.htm>

异常处理是处理程序中可能发生的异常的过程。异常只是提供了一种将控制从程序的一部分转移到另一部分的方法。

C++ 异常处理建立在这里给出的三个关键字之上:

*   try 块标识一个代码块，特定的异常将被激活。
*   **catch** -一个程序在程序中你希望 处理问题的地方用异常处理程序捕获一个异常。
*   当一个问题出现时，一个程序抛出一个异常。这是使用关键字 throw 完成的。

下面是使用 try/catch 块的语法:

```
try
{
   // protected code
}catch(ExceptionName exc1)
{
   // catch block
}catch(ExceptionName exc2)
{
   // catch block
}catch(ExceptionName excN)
{
   // catch block
}
```

## C++ 异常处理示例

下面是一个示例程序，实际说明了 C++ 中异常处理的概念:

```
/* C++ Exception Handling - Example Program */

#include<iostream.h>
#include<conio.h>
void main()
{
   clrscr();
   int num;
   cout<<"Enter a number: ";
   cin>>num;
   cout<<"Before try\n";
   try
   {
      cout<<"Insice try\n";
      if(num<0)
      {
         throw num;
         cout<<"After throw (never executed)\n";
      }
   }catch(int num)
   {
      cout<<"Exception caught\n";
   }
   cout<<"After catch (will be executed)\n";
   getch();
}
```

下面是上述 C++ 程序的运行示例:

```
Enter a number: -1
Before try
Inside try
Exception caught
After catch (will be executed)
```

[C++ 在线测试](/exam/showtest.php?subid=3)

* * *

* * *